const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const phases=[['1','Staff + keyboard foundations',1,14],['2','Note reading + rhythm fluency',15,30],['3','Melody + fingering',31,45],['4','Two hands + chords',46,60],['5','Sight-reading + song building',61,75],['6','Song independence',76,90]];
const titles=['Keyboard geography + landmarks','Treble clef: lines and spaces','Bass clef: lines and spaces','Steps, skips and repeats','Quarter, half and whole notes','Count 4/4 aloud','Right-hand five-finger patterns','Left-hand landmarks','Treble + bass together','Read short patterns','Simple melodies','Finger numbers','Phrase shapes','Review + mini assessment'];
const songs=[['ode','Ode to Joy','Beethoven','Public domain','C4','C4 D4 E4 F4 G4 G4 F4 E4 D4 C4 C4 D4 D4'],['amazing','Amazing Grace','Traditional','Public domain','G4','G4 C5 E5 C5 E5 D5 C5 A4 G4'],['joy','Joy to the World','Handel','Public domain','C4','C5 B4 A4 G4 F4 E4 D4 C4'],['jingle','Jingle Bells','Traditional','Public domain','E4','E4 E4 E4 E4 E4 E4 E4 G4 C4 D4 E4']].map(x=>({id:x[0],title:x[1],composer:x[2],type:x[3],first:x[4],notes:x[5].split(' ')}));
const state=JSON.parse(localStorage.getItem('keys10')||'{"day":1,"completed":[],"note":{"correct":0,"total":0},"rhythm":{"correct":0,"total":0},"songs":[],"results":[]}');
let step=0,timer=null,left=600,target='C4',tap=[];
function save(){localStorage.setItem('keys10',JSON.stringify(state))}function phase(d){return phases.find(p=>d>=p[2]&&d<=p[3])||phases[0]}function today(){return {day:state.day,title:titles[(state.day-1)%titles.length],focus:phase(state.day)[1]}}
function renderHome(){let d=today();$('#dayNumber').textContent=d.day;$('#lessonDay').textContent=d.day;$('#todayTitle').textContent=d.title;$('#todayDesc').textContent=d.focus;$('#noteScore').textContent=state.note.total?Math.round(state.note.correct/state.note.total*100)+'%':'—';$('#rhythmScore').textContent=state.rhythm.total?Math.round(state.rhythm.correct/state.rhythm.total*100)+'%':'—';$('#songCount').textContent=state.songs.length;$('#roadmap').innerHTML=phases.map(p=>`<div class="phase ${d.day>=p[2]&&d.day<=p[3]?'current':''}"><b>${p[0]}. ${p[1]}</b><span>Days ${p[2]}–${p[3]}</span></div>`).join('')}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));if(id==='home')renderHome();if(id==='progress')renderProgress()}
$$('.nav').forEach(x=>x.onclick=()=>show(x.dataset.screen));$('#startLesson').onclick=startLesson;$('#backHome').onclick=()=>{stop();show('home')};$('#songsHome').onclick=()=>show('home');$('#progressHome').onclick=()=>show('home');$('#resetBtn').onclick=()=>{if(confirm('Reset all progress?')){localStorage.removeItem('keys10');location.reload()}};
function startLesson(){step=0;left=600;show('lesson');renderStep();startTimer()}function startTimer(){stop();timer=setInterval(()=>{left=Math.max(0,left-1);$('#timer').textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0')},1000)}function stop(){if(timer){clearInterval(timer);timer=null}}
$('#prevStep').onclick=()=>{if(step){step--;renderStep()}};$('#nextStep').onclick=()=>{if(step<4){step++;renderStep()}else completeDay()};
function renderStep(){let f=[learn,notes,rhythm,play,test][step];$('#lessonTitle').textContent=today().title;$('#lessonProgress').style.width=((step+1)*20)+'%';$('#prevStep').disabled=!step;$('#nextStep').textContent=step===4?'Finish day →':'Next →';$('#lessonStep').innerHTML=f();if(step===1)setupNotes();if(step===2)setupRhythm();if(step===3)setupPlay()}
function learn(){return `<span class="eyebrow">1 / 5 · LEARN</span><h2>${today().title}</h2><p>Today's focus is <b>${today().focus}</b>. The key skill is connecting what you see on the staff to the physical keyboard.</p><div class="concept"><b>Reading rule:</b> Look for landmarks, then recognize steps, skips, repeats and familiar shapes. Do not stop to spell every note forever.</div><h3>10-minute structure</h3><ol><li>Learn one concept.</li><li>Read a few notes.</li><li>Count a simple rhythm.</li><li>Play slowly at the piano.</li><li>Finish with a quick check.</li></ol>`}
function notes(){return `<span class="eyebrow">2 / 5 · STAFF READING</span><h2>See it. Name it. Find it.</h2><p>Identify the note, then play that pitch on your piano.</p><div class="note-area"><div class="staff-wrap" id="staff"></div><div><div class="answers" id="answers"></div><div class="feedback" id="noteFeedback"></div><p>Landmarks: Treble G is the second line. Middle C sits just below treble and just above bass.</p></div></div>`}
function noteMidi(n){let m=n.match(/^([A-G])(\d)$/);let map={C:0,D:2,E:4,F:5,G:7,A:9,B:11};return (+m[2]+1)*12+map[m[1]]}function noteName(m){return ['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][m%12]+(Math.floor(m/12)-1)}function shuffle(a){return a.sort(()=>Math.random()-.5)}
function staffSVG(note){let l=note[0],o=+note[1],pos={C:0,D:1,E:2,F:3,G:4,A:5,B:6}[l]+(o-4)*7,y=150-pos*8;let lines=[50,70,90,110,130].map(v=>`<line x1="40" y1="${v}" x2="460" y2="${v}" stroke="#667085"/>`).join('');return `<svg viewBox="0 0 500 210"><text x="48" y="116" font-size="82" font-family="serif">𝄞</text>${lines}<ellipse cx="240" cy="${y}" rx="12" ry="9" fill="#111827" transform="rotate(-18 240 ${y})"/><line x1="250" y1="${y}" x2="250" y2="${y-55}" stroke="#111827" stroke-width="2"/></svg>`}
function setupNotes(){let pool=['C4','D4','E4','F4','G4','A4','B4','C5','D5','E5'];target=pool[Math.floor(Math.random()*pool.length)];$('#staff').innerHTML=staffSVG(target);let ans=shuffle([...new Set([noteName(noteMidi(target)),...shuffle(pool).slice(0,3).map(x=>noteName(noteMidi(x)))])]).slice(0,3);$('#answers').innerHTML=ans.map(x=>`<button class="answer" data-n="${x}">${x}</button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>answer(b))}function answer(b){let want=noteName(noteMidi(target));state.note.total++;if(b.dataset.n===want){state.note.correct++;b.classList.add('correct');$('#noteFeedback').textContent='✓ Correct — now play that pitch on your piano.';$$('.answer').forEach(x=>x.disabled=true)}else{b.classList.add('wrong');$('#noteFeedback').textContent='Try again. Use the note position and staff landmarks.'}save();renderHome()}
function rhythm(){return `<span class="eyebrow">3 / 5 · RHYTHM</span><h2>Keep the pulse.</h2><p>Tap four steady beats. Think <b>1 2 3 4</b>. Quarter note = 1 beat; half note = 2; whole note = 4.</p><div class="rhythm-pad">${[1,2,3,4].map(i=>`<button class="beat">${i}</button>`).join('')}</div><div id="rhythmFeedback" class="feedback"></div>`}function setupRhythm(){tap=[];$$('.beat').forEach(b=>b.onclick=()=>{b.classList.add('hit');setTimeout(()=>b.classList.remove('hit'),100);tap.push(performance.now());if(tap.length===4){let ds=tap.slice(1).map((x,i)=>x-tap[i]),avg=ds.reduce((a,b)=>a+b,0)/3,v=Math.sqrt(ds.reduce((a,b)=>a+(b-avg)**2,0)/3),score=Math.max(0,Math.min(100,100-v/5));state.rhythm.total++;if(score>=70)state.rhythm.correct++;save();$('#rhythmFeedback').textContent=`${score>=70?'✓ Nice pulse':'Keep practicing'} — ${Math.round(score)}% consistency.`;renderHome()}})}
function play(){let s=songs[(state.day-1)%songs.length];return `<span class="eyebrow">4 / 5 · PLAY</span><h2>Turn reading into music.</h2><p>Practice a tiny melody from <b>${s.title}</b>. Go slowly and keep the beat.</p><div class="staff-wrap">${staffSVG(s.first)}</div><div class="keyboard" id="keyboard"></div><div class="concept">Today's goal is not speed. Read a pattern, find it on the keyboard, and keep moving.</div>`}function setupPlay(){let el=$('#keyboard'),white=['C','D','E','F','G','A','B','C','D','E','F','G','A','B'];el.innerHTML=white.map(x=>`<div class="white-key" data-n="${x}">${x}</div>`).join('');$$('#keyboard .white-key').forEach(k=>k.onclick=()=>tone(noteMidi(k.dataset.n+'4')))}function tone(m){let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.value=440*Math.pow(2,(m-69)/12);g.gain.value=.12;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.5)}
function test(){return `<span class="eyebrow">5 / 5 · QUICK CHECK</span><h2>Say the rules out loud.</h2><ol><li>Look for landmarks and patterns instead of spelling every note.</li><li>A half note gets two beats in 4/4.</li><li>If you make a mistake while sight-reading, keep the pulse and continue.</li></ol><div class="concept"><b>You're building:</b> note recognition → rhythm → keyboard geography → recognizable songs.</div>`}
function completeDay(){stop();let d=state.day;if(!state.completed.includes(d))state.completed.push(d);state.results.unshift({day:d,date:new Date().toLocaleDateString(),note:state.note.total?Math.round(state.note.correct/state.note.total*100):0,rhythm:state.rhythm.total?Math.round(state.rhythm.correct/state.rhythm.total*100):0});if(state.day<90)state.day++;save();renderHome();show('home');toast(`Day ${d} complete.`)}
function renderSongs(){$('#songGrid').innerHTML=songs.map(s=>`<div class="song"><span class="eyebrow">${s.type}</span><h3>${s.title}</h3><p>${s.composer}</p><button class="secondary" onclick="practiceSong('${s.id}')">Practice melody</button></div>`).join('')}function practiceSong(id){let s=songs.find(x=>x.id===id);if(!state.songs.includes(id))state.songs.push(id);save();show('lesson');$('#lessonTitle').textContent=s.title;$('#lessonDay').textContent='LAB';$('#lessonProgress').style.width='100%';$('#lessonStep').innerHTML=`<span class="eyebrow">SONG LAB</span><h2>${s.title}</h2><p>${s.composer} · ${s.type}</p><div class="staff-wrap">${staffSVG(s.first)}</div><p><b>Opening notes:</b> ${s.notes.slice(0,12).map(x=>noteName(noteMidi(x))).join(' · ')}</p><div class="keyboard" id="keyboard"></div>`;$('#prevStep').disabled=true;$('#nextStep').disabled=true;setupPlay()}
function renderProgress(){let n=state.note.total?Math.round(state.note.correct/state.note.total*100):0,r=state.rhythm.total?Math.round(state.rhythm.correct/state.rhythm.total*100):0;$('#metricCards').innerHTML=[['Days completed',state.completed.length+'/90'],['Note reading',n+'%'],['Rhythm',r+'%']].map(x=>`<div class="metric-card"><span class="eyebrow">${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#results').innerHTML=state.results.slice(0,10).map(x=>`<div class="result"><span>Day ${x.day} · ${x.date}</span><span>Notes ${x.note}% · Rhythm ${x.rhythm}%</span></div>`).join('')||'<p>No completed lessons yet.</p>'}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
renderHome();renderSongs();renderProgress();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});window.practiceSong=practiceSong;